# Generated by Django 3.2.7 on 2026-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analyzing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meternumber', models.CharField(max_length=150)),
                ('currentreading', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('bill_amount', models.CharField(max_length=150)),
                ('due_date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('cid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('receiver', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerid', models.CharField(max_length=150)),
                ('complaintname', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('photoss', models.FileField(max_length=150, upload_to='')),
                ('status', models.CharField(max_length=150)),
                ('cid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='consumerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('meter_number', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meternumber', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('post_date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymenttype', models.CharField(max_length=150)),
                ('bill_amount', models.CharField(max_length=150)),
                ('cardnum', models.CharField(max_length=150)),
                ('ccvnum', models.CharField(max_length=150)),
                ('expdate', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('cardname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
