# Generated by Django 3.2.7 on 2026-03-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_add_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
            ],
        ),
    ]
