# Generated by Django 3.2.7 on 2026-03-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_dispatch_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerid', models.CharField(max_length=150)),
                ('zoneid', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=500)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='details',
            field=models.CharField(default='No details provided', max_length=250),
        ),
    ]
