# Generated by Django 3.2.7 on 2026-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20260315_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('new_name', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=150)),
                ('status', models.CharField(default='Pending', max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NewConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('connection_type', models.CharField(max_length=150)),
                ('status', models.CharField(default='Pending', max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SolarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('solar_capacity', models.CharField(max_length=150)),
                ('status', models.CharField(default='Pending', max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TariffChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('current_plan', models.CharField(max_length=150)),
                ('new_plan', models.CharField(max_length=150)),
                ('status', models.CharField(default='Pending', max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='is_alert',
            field=models.BooleanField(default=False),
        ),
    ]
