# Generated by Django 3.2.7 on 2026-03-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_auto_20260315_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('current', models.FloatField(default=0.0)),
                ('power', models.FloatField(default=0.0)),
                ('energy', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
