# Generated by Django 3.2.7 on 2026-03-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_energymonitoring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnergyMonitoring',
            new_name='energy_data',
        ),
    ]
