# Generated by Django 3.2.7 on 2026-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_chat_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='newconnection',
            name='phase',
            field=models.CharField(default='1-Phase', max_length=150),
        ),
    ]
