# Generated by Django 3.2.7 on 2026-04-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0009_newconnection_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='zone',
            field=models.CharField(default='All Zones', max_length=150),
        ),
    ]
